name: Deploy Worker Script

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Replace Environmental Variables
        run: |
          sed -i 's\${PROJECT_NAME}\${{ github.repository_owner }}\g' cloudflare-worker/wrangler.toml
          sed -i 's\${TARGET_DOMAIN}\${{ vars.TARGET_DOMAIN }}\g' cloudflare-worker/wrangler.toml
          sed -i 's\${SERVE_DOMAIN}\${{ vars.SERVE_DOMAIN }}\g' cloudflare-worker/wrangler.toml
          
      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          workingDirectory: "cloudflare-worker"
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
